language: android
jdk: oraclejdk8

android:
  components:

    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

  licenses:
    - android-sdk-license-.+

    

script:
    - ./gradlew clean assemble generateDebugSources compileDebugSources mockableAndroidJar compile
DebugUnitTestSources testDebug --stacktrace

notifications:
    slack: cmput301workspace:jkhKYjcVi1WZeI6rbCjj5Icu
